# Generated by Django 3.1.7 on 2021-02-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wezom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostauto',
            name='number',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
