# Generated by Django 3.1.7 on 2021-02-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wezom', '0002_lostauto_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostauto',
            options={'verbose_name': 'Lost auto', 'verbose_name_plural': 'Losts auto'},
        ),
    ]
