# Generated by Django 3.1.7 on 2021-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wezom', '0005_auto_20210225_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
