# Generated by Django 3.1.7 on 2021-02-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wezom', '0006_auto_20210225_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wezom.brand'),
        ),
        migrations.AlterField(
            model_name='lostauto',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_auto', to='wezom.brand'),
        ),
        migrations.AlterField(
            model_name='lostauto',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_auto', to='wezom.model'),
        ),
    ]
